name: Convert README to HTML

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Copy readme to index.html
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    steps:
      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: index.html
          github-corners: https://github.com/benjisoft/benjisoft
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌐</text></svg>