name: Generate Snake GIF

on:
  schedule: # execute every 12 hours
    - cron: "0 */3 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Generating and saving snake SVG
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Snake Animation
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: benjisoft
          outputs: "dist/github-contribution-grid-snake.svg"
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [-z "$(git status --porcelain)"]; then
              echo "::set-output name=push::false"
          else
              git commit -m "Add changes" -a
              echo "::set-output name=push::true"
          fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}